In [15]:
import os
import pandas as pd

In [16]:
# Base folder
folder_path = './data'  # Use './data' if you're running notebook from project root

In [17]:


# Create the list to collect all DataFrames
all_data = []

# Go through each year folder
for year in sorted(os.listdir('./data')):
    year_path = os.path.join('./data', year)
    if os.path.isdir(year_path):
        # Loop through each month folder (e.g., 'June2020TransBorderRawData')
        for month_folder in sorted(os.listdir(year_path)):
            month_path = os.path.join(year_path, month_folder)
            if os.path.isdir(month_path):
                # Loop through each CSV file in the month folder
                for file in os.listdir(month_path):
                    if file.endswith('.csv'):
                        file_path = os.path.join(month_path, file)
                        try:
                            # Read CSV with low_memory=False to handle mixed data types
                            df = pd.read_csv(file_path, low_memory=False)
                            df['year'] = year
                            df['month_folder'] = month_folder
                            df['source_file'] = file
                            all_data.append(df)
                        except Exception as e:
                            print(f"⚠️ Error loading {file_path}: {e}")

# After all files are loaded, combine into one DataFrame
if all_data:
    combined_df = pd.concat(all_data, ignore_index=True)
    print(f"✅ Loaded {len(all_data)} CSV files. Final shape: {combined_df.shape}")
    display(combined_df.head())
else:
    print("❌ No CSV files loaded. Please check folder structure and paths.")

✅ Loaded 21 CSV files. Final shape: (2051251, 18)

,TRDTYPE,USASTATE,DEPE,DISAGMOT,MEXSTATE,CANPROV,COUNTRY,VALUE,SHIPWT,FREIGHT_CHARGES,DF,CONTCODE,MONTH,YEAR,year,month_folder,source_file,COMMODITY2
0,1,AK,0712,5,NaN,XQ,1220,12182,0,461,1.0,X,7,2020,2020,July2020TransBorderRawData,dot1_0720.csv,NaN
1,1,AK,20XX,3,NaN,XA,1220,29921,1209,202,1.0,X,7,2020,2020,July2020TransBorderRawData,dot1_0720.csv,NaN
2,1,AK,20XX,3,NaN,XA,1220,2590,16,74,2.0,X,7,2020,2020,July2020TransBorderRawData,dot1_0720.csv,NaN
3,1,AK,20XX,3,NaN,XC,1220,58967,7843,857,1.0,X,7,2020,2020,July2020TransBorderRawData,dot1_0720.csv,NaN
4,1,AK,20XX,3,NaN,XC,1220,7201,1,133,2.0,X,7,2020,2020,July2020TransBorderRawData,dot1_0720.csv,NaN

In [18]:
df.tail()

,TRDTYPE,DEPE,COMMODITY2,DISAGMOT,COUNTRY,VALUE,SHIPWT,FREIGHT_CHARGES,DF,CONTCODE,MONTH,YEAR,year,month_folder,source_file
17140,2,55XX,98,5,1220,4384342,7399,1883,NaN,0,9,2024,2024,september2024,dot3_0924.csv
17141,2,55XX,98,8,1220,50211,6350,3500,NaN,0,9,2024,2024,september2024,dot3_0924.csv
17142,2,60XX,89,8,1220,793390,80,500,NaN,0,9,2024,2024,september2024,dot3_0924.csv
17143,2,70XX,99,8,1220,233990301,0,0,NaN,0,9,2024,2024,september2024,dot3_0924.csv
17144,2,70XX,99,8,2010,224981722,0,0,NaN,0,9,2024,2024,september2024,dot3_0924.csv